on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of machine to run the jobs on
        required: false
        type: string
        default: ubuntu-latest

      environment:
        description: The environment that the deploy job references
        required: true
        type: string

      registry_login_server:
        description: Login server of container registry
        required: true
        type: string

      registry_repository:
        description: Repository in container registry to push Docker image to
        required: true
        type: string

      webapp_name:
        description: Name of Azure Web App to deploy Docker image to
        required: true
        type: string

    secrets:
      registry_username:
        description: Username used to login to container registry
        required: true

      registry_password:
        description: Password used to login to container registry
        required: true

      webapp_publish_profile:
        description: Publish Profile used to authenticate to Azure Web App
        required: true

env:
  TAG_COMMIT_SHA: ${{ inputs.registry_login_server }}/${{ inputs.registry_repository }}:${{ github.sha }}
  TAG_LATEST: ${{ inputs.registry_login_server }}/${{ inputs.registry_repository }}:latest

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t ${{ env.TAG_COMMIT_SHA }} -t ${{ env.TAG_LATEST }}

      - name: Login to container registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.registry_login_server }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Push Docker image to container registry
        run: |
          docker push ${{ env.TAG_COMMIT_SHA }}
          docker push ${{ env.TAG_LATEST }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ${{ inputs.runs-on }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy Docker image to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.webapp_name }}
          publish-profile: ${{ secrets.webapp_publish_profile }}
          images: ${{ env.TAG_COMMIT_SHA }}
